version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL:-http://0.0.0.0:3001}
      - REACT_APP_ENVIRONMENT=${REACT_APP_ENVIRONMENT:-development}
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3001}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3000}
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  node_modules_frontend:
  node_modules_backend: