version: '3.8'

services:
  frontend:
    image: ${DOCKER_USERNAME}/avatar-meeting-frontend:latest
    restart: unless-stopped
    environment:
      - REACT_APP_BACKEND_URL=${BACKEND_URL}
      - NODE_ENV=production

  backend:
    image: ${DOCKER_USERNAME}/avatar-meeting-backend:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
    expose:
      - "3001"

  nginx:
    image: ${DOCKER_USERNAME}/avatar-meeting-nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

networks:
  default:
    driver: bridge